# Sharded Repodata Report

This report creates several charts which will be used in the conda.org blog post for sharded repodata.

In [3]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [8]:
def get_profiled_agg(file):
    # Load the CSV file
    df = pd.read_csv(file)
    
    # Convert time columns from nanoseconds to seconds for better readability
    df['total_time_sec'] = df['total_time'] / 1e9
    
    # Convert memory from bytes to MB
    df['max_memory_mb'] = df['max_memory_usage'] / (1024 * 1024)
    
    # Convert bytes to MB
    df['bytes_recv_mb'] = df['bytes_recv'] / (1024 * 1024)
    df['bytes_sent_mb'] = df['bytes_sent'] / (1024 * 1024)
    
    # Filter out setup and tear-down commands
    profiled = df[df["name"].str.startswith("conda_create")]
    
    # Columns we need for report
    columns = [
        "name",
        "bytes_recv",
        "bytes_sent",
        "user_time",
        "cpu_time",
        "total_time",
        "max_memory_usage",
        "total_time_sec",
        "max_memory_mb",
        "bytes_recv_mb",
        "bytes_sent_mb"
    ]
    
    profiled_agg = profiled[columns].groupby("name").mean()

    return profiled_agg

In [9]:
profiled_agg_libmamba = get_profiled_agg('../data/sharded_repodata_performance_2025-11-20.csv')

In [10]:
profiled_agg_libmamba

,bytes_recv,bytes_sent,user_time,cpu_time,total_time,max_memory_usage,total_time_sec,max_memory_mb,bytes_recv_mb,bytes_sent_mb
name,,,,,,,,,,
conda_create_conda_forge_cold_datascience,7.352846e+07,927256.0,13.330000,6.143333,6.603137e+10,1.718619e+09,66.031372,1639.002604,70.122203,0.884300
conda_create_conda_forge_cold_python,7.341209e+07,839732.0,13.566667,5.346667,6.201466e+10,1.727178e+09,62.014663,1647.165365,70.011220,0.800831
conda_create_conda_forge_sharded_cold_datascience,2.061544e+06,153827.0,0.503333,0.120000,3.186102e+09,1.083856e+08,3.186102,103.364583,1.966041,0.146701
conda_create_conda_forge_sharded_cold_python,1.359357e+06,65164.0,0.303333,0.100000,2.185206e+09,1.084675e+08,2.185206,103.442708,1.296384,0.062145
conda_create_conda_forge_sharded_warm_datascience,0.000000e+00,0.0,0.276667,0.030000,1.010844e+09,1.100732e+08,1.010844,104.973958,0.000000,0.000000
conda_create_conda_forge_sharded_warm_python,0.000000e+00,0.0,0.093333,0.006667,6.704537e+08,3.348343e+07,0.670454,31.932292,0.000000,0.000000
conda_create_conda_forge_warm_datascience,0.000000e+00,0.0,8.836667,2.366667,1.159447e+10,1.722270e+09,11.594470,1642.484375,0.000000,0.000000
conda_create_conda_forge_warm_python,0.000000e+00,0.0,8.616667,2.080000,1.109624e+10,1.714061e+09,11.096244,1634.656250,0.000000,0.000000

In [11]:
profiled_agg_rattler = get_profiled_agg('../data/sharded_repodata_performance_rattler_2025-11-20.csv')

In [12]:
profiled_agg_rattler

,bytes_recv,bytes_sent,user_time,cpu_time,total_time,max_memory_usage,total_time_sec,max_memory_mb,bytes_recv_mb,bytes_sent_mb
name,,,,,,,,,,
conda_create_conda_forge_cold_datascience,0.000000e+00,0.000000,0.970000,0.086667,1.516814e+09,1.037039e+08,1.516814,98.899740,0.000000,0.000000
conda_create_conda_forge_cold_python,1.673049e+07,198896.666667,1.826667,1.553333,1.256277e+10,1.732867e+08,12.562772,165.259115,15.955438,0.189683
conda_create_conda_forge_sharded_cold_datascience,2.713703e+05,7367.666667,0.073333,0.030000,8.441642e+08,3.223415e+07,0.844164,30.740885,0.258799,0.007026
conda_create_conda_forge_sharded_cold_python,2.694767e+05,6193.000000,0.023333,0.020000,6.726520e+08,1.510332e+07,0.672652,14.403646,0.256993,0.005906
conda_create_conda_forge_sharded_warm_datascience,0.000000e+00,0.000000,0.000000,0.000000,5.061839e+08,1.829547e+05,0.506184,0.174479,0.000000,0.000000
conda_create_conda_forge_sharded_warm_python,0.000000e+00,0.000000,0.000000,0.000000,5.087031e+08,1.870507e+05,0.508703,0.178385,0.000000,0.000000
conda_create_conda_forge_warm_datascience,0.000000e+00,0.000000,0.940000,0.100000,1.513066e+09,4.974278e+08,1.513066,474.384115,0.000000,0.000000
conda_create_conda_forge_warm_python,0.000000e+00,0.000000,0.446667,0.046667,1.009066e+09,1.075746e+08,1.009066,102.591146,0.000000,0.000000